### ISSUE TITLE
Very high CPU using?

### ISSUE THREAD

**Issue by YiChenCityU** [emiliofidalgo/ibow-lcd#3]
Hi, 
Thanks for your sharing.
I have test the ibow-lcd for loop detection. 
But i found  that the process cost too much cpu.
Is it normal?
The computer is Thinkpad X1 carbon with core i7 .  It cost almost 94%CPU.
Thanks very much.
![picture2](https://user-images.githubusercontent.com/12424523/44189038-c4bedb80-a153-11e8-9f7b-bbdc58f50c37.png)

**Comment by emiliofidalgo** [comment]
Hi!

Sorry for my late reply. The performance of the algorithm depends on your needs and the configuration of the corresponding parameters. Certainly, deleting features costs CPU. Several options can be performed to reduce this computational cost:

- How many features per image do you use? Perhaps you can reduce the number of keypoints per frame.

- If you are using the algorithm in a reduced enviroment and you are not worried about RAM memory, you can consider to disable the purging process (parameter purge_descriptors). This is not one of the expected behaviours of iBow-LCD, but could be useful in certain cases.

- You can also play with the number of frames that a feature should be observed to be considered as a permanent visual word (parameter min_feat_apps) . Increasing this value will reduce the number of visual words of the dynamic dictionary. However, be careful with that. This parameter can affect the recognition performance of the algorithm and should be tunned according to the overlap of consecutive frames.

I hope this helps,

Thank you for trying the code and the corresponding feedback!

**Comment by YiChenCityU** [comment]
Thanks for your reply.
I think maybe my computer has problem. I tried another computer. It didn't cost very high CPU. 
I also have another question. Does the number of the keypoints in each image has to be same? such as all should be 300, 500. 
I  tried another kind of feature detection method(goodFeatureToTrack in opencv), but I failed to run the main process. This method will return keypoints with different number each time. Am I wrong? 

``` 
-----index is : 28---size of window_brief_descriptors: 322
----descriptors_mat size: [32 x 322]
cost 0.003972 seconds
Not enough images to found a loop
-----merge cnt: 29
-----size of kps is : 322
-----index is : 29---size of dscs: [0 x 0]
-----index is : 29---size of window_brief_descriptors: 322
----descriptors_mat size: [32 x 322]
cost 0.003246 seconds
Not enough images to found a loop
-----merge cnt: 30
-----size of kps is : 356
-----index is : 30---size of dscs: [0 x 0]
-----index is : 30---size of window_brief_descriptors: 356
----descriptors_mat size: [32 x 356]
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check
Aborted (core dumped)
```

**Comment by emiliofidalgo** [comment]
You can use any number of features, but it makes sense to use more or less the same for each image since this can affect the priority of the loop closure candidates.

Regarding the error, what description method do you use? I mean, goodFeaturesToTrack is used to detect keypoints in the image, but after that, you have to describe each keypoint. OBIndex2 works with binary descriptors (ORB, BRIEF, BRISK, LDB, ...) and you should use one of these to work with iBoW-LCD.

**Comment by YiChenCityU** [comment]
I found the bug. Maybe the **index** in the process function should start from 0. 
I compute the brief descriptor after GFTT.  It worked. The accuracy was very good.

**Comment by emiliofidalgo** [comment]
Nice to hear that!

Thank you again for your feedback!
