### ISSUE TITLE
load the keypoints and descriptors not work.

### ISSUE THREAD

**Issue by YiChenCityU** [emiliofidalgo/ibow-lcd#4]
Hi, 
I have use XML to save/ load the keypoints and descriptors . When I load it. The new image cannot find the  loop in the previous map. I have changed the p in the ibow::lcdetector::params to be the number of the images in the XML as below shows.
![screenshot 2018-08-24 15 09 03](https://user-images.githubusercontent.com/12424523/44570612-09c8ba80-a7b1-11e8-8887-1d5e5a3004bf.png)

**Comment by emiliofidalgo** [comment]
Hi!

The _p_ parameter is not the number of images in the XML. It is the number of recent frames that should be discarded as plausible loop candidates to avoid closing loops between consecutive frames, as indicated in the paper. Therefore, this parameters should be set to a reasonable value to avoid closing loops with these recent frames.

Regarding the XML, I am not sure what are you trying to do. If you save a set of keypoints previously in a file and, in another execution, you load these descriptors correctly, it should be transparent for the algorithm. It does not depend if you compute keypoint descriptors on each execution or you load them from a file.

Regards,
