### ISSUE TITLE
Precision-recall different curve on different runs

### ISSUE THREAD

**Issue by gs14iitbbs** [emiliofidalgo/ibow-lcd#7]
Hi @emiliofidalgo,

I am able to run the code successfully on the Lip6Indoor dataset. But every time I evaluate (using rosrun ibow-lcd evaluator $Path$/evaluation/configs/debug/config_Lip6In.json), I get different data in loops.txt file. 

Is it because of randomness in feature extraction? Otherwise what causes this variance?

This leads to a different PR curve (inferior recall performance) as compared to the one given in the paper. 

This is what I get in one of the run:

![our_ibow](https://user-images.githubusercontent.com/25165333/99671126-8f309780-2aac-11eb-94f2-d72c7d96afc6.png)

While in the paper it is something like this:

![PR_paper_ibow](https://user-images.githubusercontent.com/25165333/99671131-8fc92e00-2aac-11eb-876b-28d17207659c.png)

Is it supposed to be varying that much or I am doing wrong?

**Comment by emiliofidalgo** [comment]
Hi @gs14iitbbs!

Sorry for my late reply. It seems correct. Note that the algorithm includes some steps that can introduce some randonmness and the result may vary:
- Feature extraction can generate a different set of features, depending on the parameters used.
- Creating search trees using OBIndex2. This step chooses randomly the tree roots and I think this can be the most critical reason.
- To be honest, I do not remember if the files included in the repository are the final ones that we used to generate the results we show in the paper.

The difference you obtain for L6I seems to be reasonable. I find it a little strange the results you show for the NC. Are you using the left and right images together, as indicated in the paper and the indicated GT files?

**Comment by gs14iitbbs** [comment]
Thanks @emiliofidalgo  for the kind response :)


>  I find it a little strange the results you show for the NC. Are you using the left and right images together, as indicated in the paper and the indicated GT files?

The NC dataset includes "images directory"  which contains sequentially numbered images, where, left images are numbered as "1,3,5... " and right images are numbered as "2,4,6,...". Therefore total 2146 images. 
I think the images are continuously fed, one by one. I didn't modify anything in this code.

The resulting loop file contains "2146 entries"  and the groundtruth.mat is of size "2146 x 2146".

Therefore, I suppose stereo images are used here.
 
Thanks!!

**Comment by emiliofidalgo** [comment]
Oh! Sorry for the confusion. I though It was explained in the paper, but it seems it is in another one:

https://ieeexplore.ieee.org/document/7938750

The NC results were obtained using both cameras, integrating left / right cameras in an image. Therefore, the GT should be reduced to half size using even or odd rows. Another option is to use just left or right cameras with the same modified GT.

Hope this helps,

Regards,

**Comment by gs14iitbbs** [comment]
That's fine. Thanks for the clarification. I will do that. 
I will post my response to this if it solves the problem.

For now we can close the issue.
