### ISSUE TITLE
Couldn't find executable named demo

### ISSUE THREAD

**Issue by ncgoh** [emiliofidalgo/ibow-lcd#8]
Hi, I am new to this and came across ibow-lcd during a project and want to try it out but I've ran into a problem.
I did exactly as the installation guide but when i try to run the demo by using [rosrun ibow-lcd demo /directory/of/images], 
ROS returns [[rosrun] couldn't find executable named demo below /home/robo/catkin_ws/src/ibow-lcd]
Any idea on what might be wrong?

I'm using ros kinetic on ubuntu 16.04.6.

**Comment by emiliofidalgo** [comment]
Hi @ncgoh,

1. Please, make sure the compilation procedure is correct, for OBIndex2 and iBoW. If this is correct, ROS should find the executable.
2. Try to execute: _rospack profile_ to update your workspace after compilation.

Regards,

**Comment by ncgoh** [comment]
Sorry for the late reply, I solve the problem already.
Thanks you so much for the reply!
